# -*- coding: utf-8 -*-
"""Student_Performance_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TfcNV_LU9Hd8iLnOJ2XqQLu8fctfz8bF

# 1. Environment Setup
Install necessary Python packages.
"""

!pip install Faker pandas numpy matplotlib seaborn

"""# 2. Imports and Configuration
Import libraries and set seeds for reproducibility.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import random
from faker import Faker
import heapq

np.random.seed(42)
random.seed(42)
fake = Faker()
sns.set(style='whitegrid')
print("Setup complete!")

"""# 3. Data Generation
Create a synthetic dataset of 250 students.
"""

n_students = 250
names = [fake.name() for _ in range(n_students)]

data = {
    'StudentID': range(1, n_students + 1),
    'Name': names,
    'Gender': np.random.choice(['Male', 'Female'], n_students),
    'Department': np.random.choice(['CSE', 'IT', 'ECE'], n_students, p=[0.4, 0.3, 0.3]),
    'Year': np.random.choice(['1st', '2nd', '3rd'], n_students),
    'Maths': np.random.normal(75, 15, n_students).clip(0, 100).astype(int),
    'Science': np.random.normal(72, 16, n_students).clip(0, 100).astype(int),
    'English': np.random.normal(78, 14, n_students).clip(0, 100).astype(int),
    'Attendance': np.random.normal(85, 10, n_students).clip(50, 100).astype(int),
    'Internal_Marks': np.random.normal(18, 4, n_students).clip(0, 25).astype(int)
}

df = pd.DataFrame(data)
df.to_csv('students.csv', index=False)
print("Dataset generated!")
print(df[['StudentID', 'Name', 'Department']].head())
print(f"Shape: {df.shape}")

"""# 4. Data Cleaning
Handle missing values and calculate total scores/grades.
"""

mask = np.random.rand(len(df)) < 0.05
df.loc[mask, ['Maths', 'Attendance']] = np.nan

print("Missing values before:\n", df.isnull().sum())

df['Maths'] = df['Maths'].fillna(df['Maths'].mean())
df['Attendance'] = df['Attendance'].fillna(df['Attendance'].median())

df['Total_Marks'] = df[['Maths', 'Science', 'English']].sum(axis=1)
df['Average'] = df['Total_Marks'] / 3
df['Grade'] = pd.cut(df['Average'], bins=[0, 50, 75, 100], labels=['Fail', 'Pass', 'Distinction'])
df['Overall_Score'] = df['Average'] * 0.7 + df['Attendance'] * 0.2 + df['Internal_Marks'] * 0.1

print("Missing values after:\n", df.isnull().sum())
print("\nData cleaning complete!")
print(df[['Grade', 'Overall_Score']].head())

"""# 5. Statistical Summary
View descriptive statistics for the numerical features.
"""

stats = df[['Maths', 'Science', 'English', 'Attendance', 'Internal_Marks', 'Average']].describe()
print("Descriptive Statistics:")
print(stats.round(2))

"""# 6. Performance Analysis
Identify top and low-performing students.
"""

def top_performers(df, top_k=10):
    heap = []
    for _, row in df.iterrows():
        score = row['Overall_Score']
        # Use sid as a tie-breaker for heap comparison
        heapq.heappush(heap, (-score, row['StudentID'], row['Name'], row['Department']))
    return heapq.nsmallest(top_k, heap)

top10 = top_performers(df)
print("Top 10 Performers (Heap Priority Queue):")
for i, (neg_score, sid, name, dept) in enumerate(top10, 1):
    print(f"{i}. {name} (ID:{sid}, {dept}): {-neg_score:.1f}")

def fail_students(df):
    fails = df[df['Grade'] == 'Fail'][['Average', 'StudentID', 'Name', 'Department']].sort_values('Average')
    return fails.head(10)

fails = fail_students(df)
print("Low Performers (Sorted List):")
for _, row in fails.iterrows():
    print(f"{row['Name']} (ID:{row['StudentID']}, {row['Department']}): {row['Average']:.1f}")

"""# 7. Departmental and Demographic Comparison
Analyze scores by Department, Gender, and Year.
"""

dept_perf = df.groupby('Department').agg({
    'Average': ['mean', 'std', 'count'],
    'Grade': lambda x: (x == 'Distinction').sum()
}).round(2)
dept_perf.columns = ['Avg_Mean', 'Avg_Std', 'Count', 'Distinctions']
print("Department-wise Performance:")
print(dept_perf)

gender_comp = df.groupby('Gender')['Average'].agg(['mean', 'std', 'count']).round(2)
year_trend = df.groupby('Year')['Average'].mean().round(2)

print("Gender-wise Comparison:")
print(gender_comp)
print("\nYear-wise Trends:")
print(year_trend)

"""# 8. Correlation Analysis
Explore relationships between attendance and grades.
"""

corr = df[['Maths', 'Science', 'English', 'Attendance', 'Internal_Marks', 'Average']].corr()
print("Key Correlations with Average Marks:")
print(corr['Average'].round(2).sort_values(ascending=False))

"""# 9. Export Report
Save summary metrics to a CSV file.
"""

report_data = {
    'Metric': ['Total Students', 'Fail Rate %', 'Distinction %', 'Overall Avg', 'Best Attendance-Marks Corr'],
    'Value': [
        len(df),
        (df['Grade']=='Fail').mean()*100,
        (df['Grade']=='Distinction').mean()*100,
        df['Average'].mean().round(2),
        corr.loc['Attendance', 'Average'].round(2)
    ]
}
report = pd.DataFrame(report_data)
report.to_csv('eda_report.csv', index=False)
print("Summary Report:")
print(report)

"""# 10. Data Visualizations
Graphical representation of student performance and trends.
"""

import matplotlib.pyplot as plt

plt.figure(figsize=(6, 5))
df['Average'].hist(bins=20, color='skyblue', edgecolor='black')
plt.title('Average Marks Distribution')
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt

plt.figure(figsize=(6, 5))
df['Grade'].value_counts().plot(kind='pie', autopct='%1.1f%%')
plt.title('Grade Distribution')
plt.ylabel('')
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt

plt.figure(figsize=(6, 5))
dept_perf['Avg_Mean'].plot(kind='bar', color='lightgreen')
plt.title('Dept Avg Performance')
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(6, 5))
sns.boxplot(data=df, x='Gender', y='Average')
plt.title('Gender vs Average')
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt

plt.figure(figsize=(6, 5))
year_trend.plot(kind='bar', color='orange')
plt.title('Year-wise Average')
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt

plt.figure(figsize=(6, 5))
plt.scatter(df['Attendance'], df['Average'], alpha=0.6, color='purple')
plt.xlabel('Attendance')
plt.ylabel('Average')
plt.title('Attendance vs Average')
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(8, 7))
sns.heatmap(corr, annot=True, cmap='coolwarm', center=0, fmt='.2f')
plt.title('Marks Correlations')
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt

plt.figure(figsize=(8, 6))
# Extract data from the top10 list generated in the previous cell
top_names = [item[2][:10] for item in top10]
top_scores = [-item[0] for item in top10]

plt.bar(range(len(top_names)), top_scores, color='gold')
plt.title('Top 10 Scores')
plt.xticks(range(len(top_names)), top_names, rotation=45, ha='right')
plt.tight_layout()
plt.show()